{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.1.jar",
          "url": "concurrentia-1.0.1.jar",
          "size": 1816001,
          "sha512": "d5c755c79feaa6ba1a069e6a3a09da0b27fad61a4798d86714beef5aab02656cb251339a0929512b83034c3057fdde76bb9014e1c99723a3c07405a8b96f00df",
          "sha256": "515019d6fef071098ee266cc85d5997f299ef7a51502b07826e2ca4c902c46ed",
          "sha1": "232308b6fa50d17b8f18039d2b3f50e178b09acb",
          "md5": "e6be984a783f9fa4aea10fccc52fee19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.1.jar",
          "url": "concurrentia-1.0.1.jar",
          "size": 1816001,
          "sha512": "d5c755c79feaa6ba1a069e6a3a09da0b27fad61a4798d86714beef5aab02656cb251339a0929512b83034c3057fdde76bb9014e1c99723a3c07405a8b96f00df",
          "sha256": "515019d6fef071098ee266cc85d5997f299ef7a51502b07826e2ca4c902c46ed",
          "sha1": "232308b6fa50d17b8f18039d2b3f50e178b09acb",
          "md5": "e6be984a783f9fa4aea10fccc52fee19"
        }
      ]
    }
  ]
}
