{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.1.jar",
          "url": "concurrentia-1.0.1.jar",
          "size": 1816001,
          "sha512": "664303a21e2b968250f65531fc499ad16cd0802a54e613758c9718408c43fbae4f43ae01f515d37b03f948dfb9fe0b6e218af69e74ea0f81ebf71cb40982ade0",
          "sha256": "c2384eea3dca9483d3ef12368883eb397af8c4821d48b486d620e07d2ddbdc08",
          "sha1": "16efcc2a191582b6e7dc169e8ff5544851c85f0c",
          "md5": "ec3d999da54e74f67ba1e2367df6b49d"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.1.jar",
          "url": "concurrentia-1.0.1.jar",
          "size": 1816001,
          "sha512": "664303a21e2b968250f65531fc499ad16cd0802a54e613758c9718408c43fbae4f43ae01f515d37b03f948dfb9fe0b6e218af69e74ea0f81ebf71cb40982ade0",
          "sha256": "c2384eea3dca9483d3ef12368883eb397af8c4821d48b486d620e07d2ddbdc08",
          "sha1": "16efcc2a191582b6e7dc169e8ff5544851c85f0c",
          "md5": "ec3d999da54e74f67ba1e2367df6b49d"
        }
      ]
    }
  ]
}
