name: 'Common Setup'
description: 'Set up JDK and grant execute permissions for gradlew'

inputs:
    java-version:
        description: 'Java version'
        required: true
        default: '21'

runs:
    using: 'composite'
    steps:
        -   name: Set up JDK
            uses: actions/setup-java@v5
            with:
                java-version: ${{ inputs.java-version }}
                distribution: 'adopt'

        -   name: Verify JDK installation
            run: java -version
            shell: bash

        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
            shell: bash
