name: 'Common Setup'
description: 'Set up JDK and grant execute permissions for gradlew'

inputs:
    java-version:
        description: 'Java version'
        required: true
        default: '21'

runs:
    using: 'composite'
    steps:
        -   name: Set up JDK for Linux and macOS
            if: runner.os != 'Windows'
            run: |
                if [ $RUNNER_OS = "Linux" ]; then
                  curl -L -o semeru.tar.gz "https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.3+9_openj9-0.44.0/ibm-semeru-open-jdk_x64_linux_21.0.3_9_openj9-0.44.0.tar.gz"
                  tar -xzf semeru.tar.gz
                  sudo mv jdk-21.0.3+9 ${{github.workspace}}/ibm-semeru-jdk
                  echo "JAVA_HOME=${{github.workspace}}/ibm-semeru-jdk" >> $GITHUB_ENV
                  echo "${{github.workspace}}/ibm-semeru-jdk/bin" >> $GITHUB_PATH
                elif [ $RUNNER_OS = "macOS" ]; then
                  curl -L -o semeru.tar.gz "https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.3+9_openj9-0.44.0/ibm-semeru-open-jdk_x64_mac_21.0.3_9_openj9-0.44.0.tar.gz"
                  tar -xzf semeru.tar.gz
                  sudo mv jdk-21.0.3+9 ${{github.workspace}}/ibm-semeru-jdk
                  echo "JAVA_HOME=${{github.workspace}}/ibm-semeru-jdk" >> $GITHUB_ENV
                  echo "${{github.workspace}}/ibm-semeru-jdk/bin" >> $GITHUB_PATH
                fi
            shell: bash

        -   name: Set up JDK for Windows
            if: runner.os == 'Windows'
            run: |
                $url = "https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.3+9_openj9-0.44.0/ibm-semeru-open-jdk_x64_windows_21.0.3_9_openj9-0.44.0.zip"
                Invoke-WebRequest -Uri $url -OutFile "semeru.zip"
                Expand-Archive -Path "semeru.zip" -DestinationPath "${{github.workspace}}\semeru"
                echo "JAVA_HOME=${{github.workspace}}\semeru\jdk-21.0.3+9" >> $env:GITHUB_ENV
                echo "${{github.workspace}}\semeru\jdk-21.0.3+9\bin" >> $env:GITHUB_PATH
            shell: pwsh

        -   name: Verify JDK installation
            run: java -version
            shell: bash

        -   name: Grant execute permission for gradlew
            if: runner.os != 'Windows'
            run: chmod +x gradlew
            shell: bash
