{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.3.jar",
          "url": "concurrentia-1.0.3.jar",
          "size": 1816001,
          "sha512": "fec574c87532ad78702c6d764debe010264f4dd9e2073dedbe57f4b4e55062bc51d725e8e75a8e1b5833434d4e224653f13c1e4d2fcdc12a833dcd7a9d731f9a",
          "sha256": "e5519105ab9f27fc7a96c71d8fe9bd4181b6838322bc34236f8fe78a010c5f91",
          "sha1": "deb3668907700e3f8626dd3f29fb6bb651a80f14",
          "md5": "b14223d691daf07b59175b4bc4b77fe7"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.3.jar",
          "url": "concurrentia-1.0.3.jar",
          "size": 1816001,
          "sha512": "fec574c87532ad78702c6d764debe010264f4dd9e2073dedbe57f4b4e55062bc51d725e8e75a8e1b5833434d4e224653f13c1e4d2fcdc12a833dcd7a9d731f9a",
          "sha256": "e5519105ab9f27fc7a96c71d8fe9bd4181b6838322bc34236f8fe78a010c5f91",
          "sha1": "deb3668907700e3f8626dd3f29fb6bb651a80f14",
          "md5": "b14223d691daf07b59175b4bc4b77fe7"
        }
      ]
    }
  ]
}
