{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.3.jar",
          "url": "concurrentia-1.0.3.jar",
          "size": 1827379,
          "sha512": "03f8761d6612338c96b3566ef6ca8506e2f523ff8480135511a8c9ebb522ec3e0bccb18f164c3809e094c4553074ba3e7446846e945f80d5c76c223f67e612e2",
          "sha256": "c1da1316a476de36c52f66b3d14c599746130472cc6fe866809efa40c4157dac",
          "sha1": "e2ebca052c7849253ee6c47ee2af0bec96567024",
          "md5": "d86dd1f6907ccec81fca1c52ad5b3ece"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.3.jar",
          "url": "concurrentia-1.0.3.jar",
          "size": 1827379,
          "sha512": "03f8761d6612338c96b3566ef6ca8506e2f523ff8480135511a8c9ebb522ec3e0bccb18f164c3809e094c4553074ba3e7446846e945f80d5c76c223f67e612e2",
          "sha256": "c1da1316a476de36c52f66b3d14c599746130472cc6fe866809efa40c4157dac",
          "sha1": "e2ebca052c7849253ee6c47ee2af0bec96567024",
          "md5": "d86dd1f6907ccec81fca1c52ad5b3ece"
        }
      ]
    }
  ]
}
