{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "FullyThreaded",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "FullyThreaded-1.0.1.jar",
          "url": "FullyThreaded-1.0.1.jar",
          "size": 1816072,
          "sha512": "3b26f79595ec657722e41ea1a6a0b8f01bc383abbd8091b8032c952412f3a1d6faea4c1f9fce2df8a1da8bfdcad388cd406037cc765ac828bf49f9bb312fbeaf",
          "sha256": "81d1dff9f8d058bba050d16e2fe2f6797d2de0adada2fd71eb6ff4e564d22b64",
          "sha1": "bd105ef51ceee9e61697de40674bbdc21114743b",
          "md5": "894c536827bbe6ed5cfa8e5e2eaa1485"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "FullyThreaded-1.0.1.jar",
          "url": "FullyThreaded-1.0.1.jar",
          "size": 1816072,
          "sha512": "3b26f79595ec657722e41ea1a6a0b8f01bc383abbd8091b8032c952412f3a1d6faea4c1f9fce2df8a1da8bfdcad388cd406037cc765ac828bf49f9bb312fbeaf",
          "sha256": "81d1dff9f8d058bba050d16e2fe2f6797d2de0adada2fd71eb6ff4e564d22b64",
          "sha1": "bd105ef51ceee9e61697de40674bbdc21114743b",
          "md5": "894c536827bbe6ed5cfa8e5e2eaa1485"
        }
      ]
    }
  ]
}
