{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.2.jar",
          "url": "concurrentia-1.0.2.jar",
          "size": 1816001,
          "sha512": "065d0cdd36f85ed7c8b21dc8cc736de128c7717a152888b16955a9ed62235af83648d41a7565fc91a1d935727cd2c62f8ce2ee07f561eb7f4caea678e56ddc9a",
          "sha256": "51d6c5264c8d2abc9dbd85d73df1425bcfea5ee6dafe0c9b032d00cb7f7a5de7",
          "sha1": "8f8e015bb4706a80699812cb830dc1e983ae499e",
          "md5": "3aca04bb851941aadcd2d6dffdb6b31a"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.2.jar",
          "url": "concurrentia-1.0.2.jar",
          "size": 1816001,
          "sha512": "065d0cdd36f85ed7c8b21dc8cc736de128c7717a152888b16955a9ed62235af83648d41a7565fc91a1d935727cd2c62f8ce2ee07f561eb7f4caea678e56ddc9a",
          "sha256": "51d6c5264c8d2abc9dbd85d73df1425bcfea5ee6dafe0c9b032d00cb7f7a5de7",
          "sha1": "8f8e015bb4706a80699812cb830dc1e983ae499e",
          "md5": "3aca04bb851941aadcd2d6dffdb6b31a"
        }
      ]
    }
  ]
}
