{
  "formatVersion": "1.1",
  "component": {
    "group": "com.altiran",
    "module": "concurrentia",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "concurrentia-1.0.2.jar",
          "url": "concurrentia-1.0.2.jar",
          "size": 1816001,
          "sha512": "68ee459a1b1dfffd26b18326a95860304cdefa9c4e5583c325a97091206baaa97a8930a720a8d56c3b13a9b85744bc40a16e42dd5c184b8e77b0fb2c1abc571e",
          "sha256": "0a78281be9fd750073cd6a182f269d7fa2b447e3c8d4979db78ece96bba0bc3a",
          "sha1": "274f1ce54f8e35fa4fea7f0d070b240dcc899614",
          "md5": "aadc84b51d7533d656e0a8b04c21caa1"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrentia-1.0.2.jar",
          "url": "concurrentia-1.0.2.jar",
          "size": 1816001,
          "sha512": "68ee459a1b1dfffd26b18326a95860304cdefa9c4e5583c325a97091206baaa97a8930a720a8d56c3b13a9b85744bc40a16e42dd5c184b8e77b0fb2c1abc571e",
          "sha256": "0a78281be9fd750073cd6a182f269d7fa2b447e3c8d4979db78ece96bba0bc3a",
          "sha1": "274f1ce54f8e35fa4fea7f0d070b240dcc899614",
          "md5": "aadc84b51d7533d656e0a8b04c21caa1"
        }
      ]
    }
  ]
}
