{
  "formatVersion": "1.1",
  "component": {
    "group": "in.electrosoft",
    "module": "FullyThreaded",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "FullyThreaded-1.0.jar",
          "url": "FullyThreaded-1.0.jar",
          "size": 5017380,
          "sha512": "907dba216f203d5ee0c80d1b624b367dbd0922a355381620e687bc301ca817e2090b544284d9f6b201ce55310afdc48f38241db96f2a17c5d0d786ff0a16b989",
          "sha256": "81b385afc2d4353a32490b469f183d44f5e68ed8fcc861711618e0bd34a2c78a",
          "sha1": "d223ed42134d37cd520db235a3dcb1bcdaec70c3",
          "md5": "0b344eec95f040652a6d7081ff6d2a5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "FullyThreaded-1.0.jar",
          "url": "FullyThreaded-1.0.jar",
          "size": 5017380,
          "sha512": "907dba216f203d5ee0c80d1b624b367dbd0922a355381620e687bc301ca817e2090b544284d9f6b201ce55310afdc48f38241db96f2a17c5d0d786ff0a16b989",
          "sha256": "81b385afc2d4353a32490b469f183d44f5e68ed8fcc861711618e0bd34a2c78a",
          "sha1": "d223ed42134d37cd520db235a3dcb1bcdaec70c3",
          "md5": "0b344eec95f040652a6d7081ff6d2a5a"
        }
      ]
    }
  ]
}
