{
  "formatVersion": "1.1",
  "component": {
    "group": "in.electrosoft",
    "module": "FullyThreaded",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "FullyThreaded-1.0.jar",
          "url": "FullyThreaded-1.0.jar",
          "size": 5017273,
          "sha512": "6b90d3da93354c2334a8e007b008254af734b009839f7c0a979121bd26886b587d07a89cc0efd2c788024237f104f83efce5aa3d1277d300e4a184b671ae9abf",
          "sha256": "bb22fd776af95cfac2c5c0d12377b773ad3b3e8010e734ff6199cbdfd8674a35",
          "sha1": "43dd895937232772a1d9d84aeb5d0dfcee20ff81",
          "md5": "0acc3f5a5e1b8f6f3af1d820e8e7dae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "FullyThreaded-1.0.jar",
          "url": "FullyThreaded-1.0.jar",
          "size": 5017273,
          "sha512": "6b90d3da93354c2334a8e007b008254af734b009839f7c0a979121bd26886b587d07a89cc0efd2c788024237f104f83efce5aa3d1277d300e4a184b671ae9abf",
          "sha256": "bb22fd776af95cfac2c5c0d12377b773ad3b3e8010e734ff6199cbdfd8674a35",
          "sha1": "43dd895937232772a1d9d84aeb5d0dfcee20ff81",
          "md5": "0acc3f5a5e1b8f6f3af1d820e8e7dae9"
        }
      ]
    }
  ]
}
